# These are supported funding model platforms

github: [intrance7]
# patreon: user-name
# open_collective: project-name
# ko_fi: user-name
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: user-name
# issuehunt: user-name
# otechie: user-name
# custom: ["https://paypal.me/your-paypal", "https://buymeacoffee.com/your-username"]
