import { useState } from 'react';
import { FileText, Download, Share2, FileJson, CheckCircle2, AlertTriangle, ArrowRight, ShieldAlert, Cpu, BrainCircuit } from 'lucide-react';
import { toast } from 'sonner';

const REPORT_TYPES = [
  { id: 'executive', name: 'Executive Report', description: 'High-level summary, risk score, and business impact. Suitable for C-suite.', icon: ShieldAlert, color: 'text-purple-400' },
  { id: 'soc', name: 'SOC Report', description: 'Actionable intelligence, IOCs, and MITRE ATT&CK mapping for Tier 1/2 analysts.', icon: AlertTriangle, color: 'text-amber-400' },
  { id: 'technical', name: 'Technical Report', description: 'Deep dive into PE sections, imports, heuristics, and disassembly.', icon: Cpu, color: 'text-blue-400' },
  { id: 'ioc', name: 'IOC Report', description: 'Strictly Indicators of Compromise formatted for SIEM ingestion.', icon: FileJson, color: 'text-emerald-400' },
  { id: 'ai', name: 'AI Summary', description: 'Narrative synthesis generated by the AI Analyst Engine.', icon: FileText, color: 'text-rose-400' },
];

export default function ReportExperience() {
  const [selectedType, setSelectedType] = useState('executive');

  const handleExport = (format: string) => {
    if (format === 'stix') {
      toast.error('STIX export is currently disabled until backend support is implemented.');
      return;
    }
    toast.success(`Generating ${format.toUpperCase()} export for ${selectedType} report...`);
  };

  return (
    <div className="p-8 max-w-5xl mx-auto w-full space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-foreground">Report Generator</h1>
        <p className="text-muted-foreground mt-1">Generate professional reports from analysis results.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Left Column: Selection */}
        <div className="space-y-6">
          <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-bold text-foreground mb-4">Select Report Type</h2>
            <div className="space-y-3">
              {REPORT_TYPES.map(type => {
                const Icon = type.icon;
                const isSelected = selectedType === type.id;
                return (
                  <div 
                    key={type.id}
                    onClick={() => setSelectedType(type.id)}
                    className={`p-4 rounded-lg border cursor-pointer transition-all flex items-start gap-4 ${isSelected ? 'bg-primary/10 border-primary shadow-md' : 'bg-muted/30 border-border hover:border-primary/50 hover:bg-muted/50'}`}
                  >
                    <div className={`p-2 rounded-md ${isSelected ? 'bg-primary/20' : 'bg-background border border-border/50'}`}>
                      <Icon className={`w-5 h-5 ${isSelected ? 'text-primary' : type.color}`} />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <h3 className={`font-bold ${isSelected ? 'text-primary' : 'text-foreground'}`}>{type.name}</h3>
                        {isSelected && <CheckCircle2 className="w-4 h-4 text-primary" />}
                      </div>
                      <p className="text-sm text-muted-foreground mt-1 leading-snug">{type.description}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right Column: Actions */}
        <div className="space-y-6">
          <div className="bg-card border border-border rounded-xl p-6 shadow-sm sticky top-8">
            <h2 className="text-lg font-bold text-foreground mb-4">Export Options</h2>
            
            <div className="bg-muted/30 rounded-lg p-4 border border-border/50 mb-6 flex items-center justify-between">
              <div>
                <span className="block text-xs uppercase font-bold text-muted-foreground tracking-wider mb-1">Target Artifact</span>
                <span className="block font-medium text-foreground">Latest Analysis (evil_sample.exe)</span>
              </div>
              <ArrowRight className="w-5 h-5 text-muted-foreground" />
            </div>

            <div className="space-y-3">
              <button 
                onClick={() => handleExport('view')}
                className="w-full flex items-center justify-center gap-2 bg-primary text-primary-foreground py-3 rounded-lg font-bold hover:bg-primary/90 transition-all shadow-md"
              >
                <FileText className="w-5 h-5" /> View Report
              </button>
              
              <button 
                onClick={() => handleExport('pdf')}
                className="w-full flex items-center justify-center gap-2 bg-card border border-border text-foreground hover:bg-muted py-3 rounded-lg font-medium transition-all"
              >
                <Download className="w-5 h-5" /> Download PDF
              </button>
              
              <button 
                onClick={() => handleExport('json')}
                className="w-full flex items-center justify-center gap-2 bg-card border border-border text-foreground hover:bg-muted py-3 rounded-lg font-medium transition-all"
              >
                <FileJson className="w-5 h-5" /> Export JSON
              </button>

              <button 
                onClick={() => handleExport('stix')}
                className="w-full flex items-center justify-center gap-2 bg-card border border-border text-muted-foreground hover:bg-muted py-3 rounded-lg font-medium transition-all relative overflow-hidden group"
              >
                <Share2 className="w-5 h-5 group-hover:opacity-0 transition-opacity" /> 
                <span className="group-hover:opacity-0 transition-opacity">Export STIX (Beta)</span>
                <span className="absolute inset-0 flex items-center justify-center bg-muted/80 backdrop-blur-sm text-foreground text-xs font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                  Backend Support Pending
                </span>
              </button>
            </div>
            
            <div className="mt-6 pt-4 border-t border-border/50">
              <button className="w-full flex items-center justify-center gap-2 text-primary hover:text-primary/80 font-medium text-sm transition-colors">
                <Share2 className="w-4 h-4" /> Share via Link
              </button>
            </div>
          </div>

          <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
            <h2 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2">
              <BrainCircuit className="w-5 h-5 text-primary" /> AI Actions
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {[
                'Explain Verdict', 'Summarize Sample', 'Explain IOC', 
                'Map to MITRE', 'Suggest Investigation Steps',
                'Generate SOC Report', 'Generate Executive Summary'
              ].map(action => (
                <button 
                  key={action}
                  onClick={() => window.dispatchEvent(new CustomEvent('open-ai-analyst', { detail: action }))}
                  className="flex items-center justify-center text-center p-3 rounded-lg border border-border bg-muted/30 hover:bg-muted hover:border-primary/50 text-xs text-foreground transition-all"
                >
                  {action}
                </button>
              ))}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
