/**
 * Generic Payment Provider Interface
 * This ensures the frontend doesn't rely directly on a specific payment gateway's implementation details.
 */
export interface PaymentProvider {
  /**
   * Initializes the checkout flow for a subscription or order.
   * @param orderId The order or subscription ID generated by the backend.
   * @param options Additional options like amount, currency, and user details.
   */
  initializeCheckout(
    orderId: string,
    options: {
      name: string;
      description: string;
      amount?: number;
      currency?: string;
      prefill?: {
        name?: string;
        email?: string;
        contact?: string;
      };
      onSuccess: (response: any) => void;
      onError: (error: any) => void;
    }
  ): void;

  /**
   * Loads the necessary scripts/SDKs for the payment provider.
   * Should be called before initializeCheckout.
   */
  load(): Promise<boolean>;
}

export class RazorpayProvider implements PaymentProvider {
  private isLoaded = false;
  private loadPromise: Promise<boolean> | null = null;
  // NOTE: This is a public key, NEVER a secret key.
  // In a real app, this might come from an environment variable.
  private readonly RAZORPAY_KEY_ID = import.meta.env.VITE_RAZORPAY_KEY_ID || 'rzp_test_mock_key';

  async load(): Promise<boolean> {
    if (this.isLoaded) return true;
    if (this.loadPromise) return this.loadPromise;

    this.loadPromise = new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => {
        this.isLoaded = true;
        resolve(true);
      };
      script.onerror = () => {
        console.error('Failed to load Razorpay SDK');
        resolve(false);
      };
      document.body.appendChild(script);
    });

    return this.loadPromise;
  }

  initializeCheckout(
    orderId: string,
    options: {
      name: string;
      description: string;
      amount?: number;
      currency?: string;
      prefill?: { name?: string; email?: string; contact?: string };
      onSuccess: (response: any) => void;
      onError: (error: any) => void;
    }
  ) {
    if (!this.isLoaded || !(window as any).Razorpay) {
      options.onError(new Error('Razorpay SDK not loaded'));
      return;
    }

    const rzpOptions = {
      key: this.RAZORPAY_KEY_ID, // Enter the Key ID generated from the Dashboard
      amount: options.amount,
      currency: options.currency || 'INR',
      name: options.name,
      description: options.description,
      order_id: orderId, // This is the order ID generated by backend
      handler: function (response: any) {
        // Backend verification is still required!
        // This is just the frontend callback.
        options.onSuccess(response);
      },
      prefill: options.prefill,
      theme: {
        color: '#3b82f6', // Tailwind blue-500
      },
    };

    const rzp = new (window as any).Razorpay(rzpOptions);
    rzp.on('payment.failed', function (response: any) {
      options.onError(response.error);
    });
    rzp.open();
  }
}
